[project]
name = 'farcana-stacks'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.farcanamini-rewarder]
path = 'contracts/farcanamini-rewarder.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
